package instancias;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jugador.*;

/**
 *
 * @author Mariano
 */
public class FrameVender extends javax.swing.JFrame {

    /**
     * Creates new form FrameVender
     */
    FondoInicio fondoVender = new FondoInicio();
    public FrameVender() {
        this.setContentPane(fondoVender);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AlimentosjLabel2 = new javax.swing.JLabel();
        MateriaPrimajLabel1 = new javax.swing.JLabel();
        LogojLabel1 = new javax.swing.JLabel();
        FinalizarJuegojButton2 = new javax.swing.JButton();
        RegresarMenuMercadojButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlimentosjLabel2.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        AlimentosjLabel2.setForeground(new java.awt.Color(0, 0, 0));
        AlimentosjLabel2.setText("Vender Alimentos");
        jPanel1.add(AlimentosjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        MateriaPrimajLabel1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        MateriaPrimajLabel1.setForeground(new java.awt.Color(0, 0, 0));
        MateriaPrimajLabel1.setText("Vender Productos");
        jPanel1.add(MateriaPrimajLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 270, 20));

        LogojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N
        jPanel1.add(LogojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, -1, -1));

        FinalizarJuegojButton2.setBackground(new java.awt.Color(255, 0, 0));
        FinalizarJuegojButton2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        FinalizarJuegojButton2.setForeground(new java.awt.Color(0, 0, 0));
        FinalizarJuegojButton2.setText("Finalizar juego");
        FinalizarJuegojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarJuegojButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(FinalizarJuegojButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, -1, -1));

        RegresarMenuMercadojButton2.setBackground(new java.awt.Color(0, 204, 204));
        RegresarMenuMercadojButton2.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        RegresarMenuMercadojButton2.setForeground(new java.awt.Color(0, 0, 0));
        RegresarMenuMercadojButton2.setText("Regresar a menu Mercado");
        RegresarMenuMercadojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuMercadojButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarMenuMercadojButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 595, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarJuegojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarJuegojButton2ActionPerformed
        JOptionPane.showMessageDialog(FrameVender.this, "Fin del juego, vuelve pronto "+Jugador.jugador1.getNick());
        System.exit(0);
    }//GEN-LAST:event_FinalizarJuegojButton2ActionPerformed

    private void RegresarMenuMercadojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuMercadojButton2ActionPerformed
        this.dispose();
        LlamadoInstancias.mercado();
    }//GEN-LAST:event_RegresarMenuMercadojButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/IrMercado.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlimentosjLabel2;
    private javax.swing.JButton FinalizarJuegojButton2;
    private javax.swing.JLabel LogojLabel1;
    private javax.swing.JLabel MateriaPrimajLabel1;
    private javax.swing.JButton RegresarMenuMercadojButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
