/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import instancias.*;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Mariano
 */
public class FrameCrearAnimales extends javax.swing.JFrame {

    /**
     * Creates new form FrameCrearAnimales
     */
    public Tiempo tiempo = new Tiempo();
    FondoInicio fondoInicio = new FondoInicio();
    public FrameCrearAnimales() {
        this.setContentPane(fondoInicio);
        initComponents();
        LlamarTiempo.tiempo();
        tiempo.start();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CrearAnimalesjLabel1 = new javax.swing.JLabel();
        IniciarJuegojButton1 = new javax.swing.JButton();
        LogojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creacion");

        jPanel1.setOpaque(false);

        CrearAnimalesjLabel1.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        CrearAnimalesjLabel1.setForeground(new java.awt.Color(0, 0, 0));
        CrearAnimalesjLabel1.setText("Creacion animales");

        IniciarJuegojButton1.setBackground(new java.awt.Color(0, 204, 204));
        IniciarJuegojButton1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        IniciarJuegojButton1.setForeground(new java.awt.Color(0, 0, 0));
        IniciarJuegojButton1.setText("Iniciar Partida");
        IniciarJuegojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarJuegojButton1ActionPerformed(evt);
            }
        });

        LogojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoracion/Logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(CrearAnimalesjLabel1)
                .addGap(320, 320, 320))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(IniciarJuegojButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogojLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(CrearAnimalesjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(IniciarJuegojButton1)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogojLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarJuegojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarJuegojButton1ActionPerformed
        this.setVisible(false);
        FrameGranja.iniciarGranja();
        FrameGranja.visible();
        
                
    }//GEN-LAST:event_IniciarJuegojButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    int minutos=0;
    int segundos=0;
    public class Tiempo extends Thread{
    @Override
    
    public void run() {
        
            for (minutos = 0;  minutos< 60; minutos++) {
                for (segundos = 0; segundos < 60; segundos++) {
                    LlamarTiempo.llamarTiempo.setLlamarMinutos(minutos);
                    LlamarTiempo.llamarTiempo.setLlamarSegundos(segundos);
                    try{
                    Thread.sleep(1000);
                    }catch(InterruptedException e){
                        System.out.println("Error en inicio tiempo "+ e);
                    }
                }
            }
    }
    public class llamarTiempo {
        
    }
    
        
    }
    class FondoInicio extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/decoracion/FondoCrearAnimales.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CrearAnimalesjLabel1;
    private javax.swing.JButton IniciarJuegojButton1;
    private javax.swing.JLabel LogojLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
